name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@13.49.75.130 << 'EOF'
            cd ~/none-corp-crm
            git pull origin main
            npm install
            npm run build

            # Nginx ko‘rayotgan papkaga build fayllarni ko‘chirish
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/
          EOF